Allow PyYAML 6.x (#214)
* Allow PyYAML 6.x

ops>=2.1.0 depends on PyYAML-6.x[0], allowing the installation of that
version in layer-basic and the charm using layer-basic can lockdown on a
more specific version of PyYAML.

It's important to keep reactive charms compatible with the ops
framework, because there are compatibility layers to allow the use of
interfaces in ops framework based charms[1]

[0] https://github.com/canonical/operator/commit/9162c873592499f512b2ea3908cf9578c0fcc4b8
[1] https://github.com/openstack/charm-interface-hacluster/commit/34b12aa480bc7d6d44699461fa21cb358c5089b4

* Fix CI

Python 3.6 is not available on github's ubuntu-latest image, the last
image with python 3.6 was ubuntu-20.04, so switch to that version to run
the linting with older versions of python on ubuntu-20.04

* Fix tox.ini [flake8].ignore

Error:

    ValueError: Error code '#' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'

* Tox 4 compatibility fixes

Replace whitelist_externals with allowlist_externals and use the full
path to the commands.

* Add Cython to wheelhouse.txt