Unpin setuptools for Python>=3.12 (#224)
* Unpin setuptools for Python>=3.12

The version of setuptools pinned by the wheelhouse is incompatible with
python 3.12, to avoid breaking old charms, this patch unpins setuptools
only for python>=3.12

Fixes the following error at build time:

      File "/tmp/pip-download-gg1zdrmr/setuptools_ebd74bdeeaf0421480a69f5448330f5e/setuptools/__init__.py", line 16, in <module>
        import setuptools.version
      File "/tmp/pip-download-gg1zdrmr/setuptools_ebd74bdeeaf0421480a69f5448330f5e/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/tmp/pip-download-gg1zdrmr/setuptools_ebd74bdeeaf0421480a69f5448330f5e/pkg_resources/__init__.py", line 2191, in <module>
        register_finder(pkgutil.ImpImporter, find_on_path)
                        ^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

* Unpin setuptools-scm

Drop anyio and sniffio for python>=3.12, this allows them to be pulled
in indirectly by whoever needs them instead of carrying them as part of
layer basic

* Set TEST_JUJU3 env variable

When TEST_JUJU3 is set, zaza will allow the use of python-libjuju>=3.0

* Allow passing TEST_* env variables